"""
Database Migration: Increase password_hash column length
This script increases the password_hash column from VARCHAR(128) to VARCHAR(256)
to accommodate longer password hashes generated by Werkzeug.
"""

import os
import sys

# Add the app directory to the Python path
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

from app import create_app, db
from sqlalchemy import text

def migrate_database():
    """Increase password_hash column length"""
    app = create_app()
    
    with app.app_context():
        try:
            print("=" * 60)
            print("  Database Migration: Increase password_hash Length")
            print("=" * 60)
            print()
            
            # Check if we're using SQLite or MySQL
            db_type = db.engine.url.drivername
            print(f"Database type detected: {db_type}")
            print()
            
            if 'sqlite' in db_type:
                print("SQLite detected. SQLite doesn't support ALTER COLUMN.")
                print("Dropping and recreating the table...")
                print()
                
                # For SQLite, we need to recreate the table
                # This is handled automatically by Flask-SQLAlchemy if we update the model
                print("Please update the User model in app/models.py:")
                print("Change: password_hash = db.Column(db.String(128), nullable=False)")
                print("To:     password_hash = db.Column(db.String(256), nullable=False)")
                print()
                print("Then run: python3 -c \"from app import create_app, db; app = create_app(); app.app_context().push(); db.drop_all(); db.create_all()\"")
                print()
                print("WARNING: This will delete all existing data!")
                
            elif 'mysql' in db_type:
                print("MySQL detected. Modifying column...")
                print()
                
                # For MySQL, we can alter the column
                alter_query = text("ALTER TABLE user MODIFY COLUMN password_hash VARCHAR(256) NOT NULL")
                
                db.session.execute(alter_query)
                db.session.commit()
                
                print("✓ Successfully increased password_hash column length to VARCHAR(256)")
                print()
                print("Migration completed successfully!")
                
            else:
                print(f"Unsupported database type: {db_type}")
                print("Please manually increase the password_hash column length to 256 characters.")
            
            print()
            print("=" * 60)
            
        except Exception as e:
            print(f"❌ Error during migration: {str(e)}")
            print()
            print("If you're using MySQL, you can manually run:")
            print("ALTER TABLE user MODIFY COLUMN password_hash VARCHAR(256) NOT NULL;")
            db.session.rollback()
            sys.exit(1)

if __name__ == '__main__':
    migrate_database()
